### ISSUE TITLE
bug??          if (num_gt := sum(label)) == 0:

### ISSUE THREAD

**Issue by Xuguozi** [TencentARC/UMT#10]
if (num_gt := sum(label)) == 0:
               ^
SyntaxError: invalid syntax

I modified the code as follow:
```
num_gt = sum(label)##add

if num_gt == 0:
    print("????????")
    collected.append(0)
    continue
```
but The map for each evaluation are different. WHY?

**Comment by yeliudev** [comment]
This is a new syntax introduced in Python 3.8 (see [here](https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions)). You may want to upgrade your Python version or modify the code as follows to run it.

```python
num_gt = sum(label)
if num_gt == 0:
    collected.append(0)
    continue
```

**Comment by yeliudev** [comment]
For the inconsistent evaluation, may I know that which command did you use to run the code?

**Comment by Xuguozi** [comment]
> 
python tools/launch.py
--config
/home/server/project/UMT/configs/youtube/umt_small_100e_youtube_dog.py
--checkpoint
/home/server/project/UMT/checkpoint/umt_small_100e_youtube_dog-90f2189e.pth
--eval

**Comment by yeliudev** [comment]
I can not reproduce your issue in my environment. Running the command you provided multiple times steadily output the same results (65.93 mAP). Could you please double-check whether you've modified other parts of the code, and whether you have the same Python & package versions as we stated in README?

**Comment by Xuguozi** [comment]
> I can not reproduce your issue in my environment. Running the command you provided multiple times steadily output the same results (65.93 mAP). Could you please double-check whether you've modified other parts of the code, and whether you have the same Python & package versions as we stated in README?

i add --seed 0 ,the map is constant, but not 65.93 mAP
```
python tools/launch.py
--config
/home/server/project/UMT/configs/youtube/umt_small_100e_youtube_dog.py
--checkpoint
/home/server/project/UMT/checkpoint/umt_small_100e_youtube_dog-90f2189e.pth
--eval
--seed
0
```

**Comment by Xuguozi** [comment]
> I can not reproduce your issue in my environment. Running the command you provided multiple times steadily output the same results (65.93 mAP). Could you please double-check whether you've modified other parts of the code, and whether you have the same Python & package versions as we stated in README?

sorry, my mistake. I didn't load the pretrained model correctly.
However, i can't get the same result (65.93map)like you. The evaluation result on as follow:

![Screenshot from 2022-05-22 21-08-15](https://user-images.githubusercontent.com/89565268/169697572-e092fc6f-80ec-4c16-b053-80903dbfd652.png)

**Comment by yeliudev** [comment]
Please retry it using exactly the same environment we used. If the problem still exists, the inconsistency may come from the difference between GPUs or CUDA versions.

**Comment by G-Apple1** [comment]
> Please retry it using exactly the same environment we used. If the problem still exists, the inconsistency may come from the difference between GPUs or CUDA versions.

Thank you very much!
