### ISSUE TITLE
Can you provide the original video data? Especially YouTube Highlights.

### ISSUE THREAD

**Issue by mxtx0509** [TencentARC/UMT#12]
It's hard for me to download the complete video data. Can you provide the original video data? Or please tell me how you download the complete data. Thank you very much.

**Comment by mxtx0509** [comment]
I used the code that ‘YouTube Highlights’   provided to download, but many videos are lost.

**Comment by yeliudev** [comment]
Some of the videos in this dataset are indeed lost now. The crawled videos that we used for this paper are available [here](https://connectpolyu-my.sharepoint.com/:u:/g/personal/21039533r_connect_polyu_hk/EfyG7Y7vJw9CsBXeDn0dlqIB9BiqnuYdN5ur3pQ9Ai_Bmw?e=96n09D) (expires Aug. 1, 2022).

**Comment by LiJiaqi96** [comment]
Thanks for your sharing! Could you please share the link of crawled videos again :)

**Comment by yeliudev** [comment]
> Thanks for your sharing! Could you please share the link of crawled videos again :)

Please use the link [here](https://connectpolyu-my.sharepoint.com/:u:/g/personal/21039533r_connect_polyu_hk/EfyG7Y7vJw9CsBXeDn0dlqIBdx7Muw_PlBHLsy9_W0Fxpg?e=MFiTaq) (expires Mar. 1, 2024).

**Comment by LiJiaqi96** [comment]
> > Thanks for your sharing! Could you please share the link of crawled videos again :)
> 
> Please use the link [here](https://connectpolyu-my.sharepoint.com/:u:/g/personal/21039533r_connect_polyu_hk/EfyG7Y7vJw9CsBXeDn0dlqIBdx7Muw_PlBHLsy9_W0Fxpg?e=MFiTaq) (expires Mar. 1, 2024).

Thanks for your sharing and timely reply!
