### ISSUE TITLE
feature exaction

### ISSUE THREAD

**Issue by Xuguozi** [TencentARC/UMT#13]
I saw in the paper that "Since each feature vector captures 32 consecutive frames, we follow and consider the feature vector belonging to a clip if their overlap is more than 50%." What is the relationship between 32 frames and 100 frames of .json annotation files? ? The feature vector of the sound is also extracted in 32 frames, and the overlap is 50%?
How to deal with sound features so that it can correspond to the characteristics of the video?

**Comment by yeliudev** [comment]
Duplicated #11. You may use the same frame rate for both audio and video features.
