### ISSUE TITLE
how to visulize the results in your paper

### ISSUE THREAD

**Issue by wenhaoHou** [TencentARC/UMT#14]
![0889e54bf4e837fd7137a3e11b4443f](https://user-images.githubusercontent.com/89185728/170901871-8245cd0e-0ea1-4d94-987c-51c38ee84f3c.png)

**Could you please send me your visual code?**

**Comment by yeliudev** [comment]
We visualized the results by manually drawing the figures. The model only outputs the moment boundaries and highlight saliency scores.
