### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by hpppppp8** [TencentARC/UMT#15]
I use the RTX 3090 to run the code, and I got the error same as title.
I google, it seems 3090 compatibility problem, it cant work with some pytorch version. Someone meets the same problem? And what is the solution?
<img width="971" alt="image" src="https://user-images.githubusercontent.com/39488872/172104700-b65f6f91-e080-4365-8517-dd33af2e864b.png">

**Comment by yeliudev** [comment]
You may try to upgrade your PyTorch version (1.10+).
