### ISSUE TITLE
How do I make my dataset

### ISSUE THREAD

**Issue by Yangaiei** [TencentARC/UMT#16]
I have a lot of questions？
   1、I want to make a data set similar to QVHighlights in my research direction,  What do I need to do?

   2、What method was used for feature extraction of QVHIGHLIGHTS text?

**Comment by yeliudev** [comment]
1. You may refer to the [QVHighlighs's paper](https://arxiv.org/abs/2107.09609) for details of data collection and annotation.
2. They used [CLIP](https://arxiv.org/abs/2103.00020) for text feature extraction.

**Comment by Yangaiei** [comment]
Thank you very much.

**Comment by Yangaiei** [comment]
Hello, questions about text feature extraction。
        1、Is the model loaded when using [CLIP](https://github.com/openai/CLIP) to extract text features VIT-B /32?
        2、Is the text input when extracting text features using CLIP the value of "query" in the "highligiht_train_release.jsonl" file?
