### ISSUE TITLE
Can you provide a demo about running predictions on my own videos and queries

### ISSUE THREAD

**Issue by hpppppp8** [TencentARC/UMT#19]
As many issues about feature extracting, I comfused about the processing. I wonder if you could provide a demo about running predictions on my own videos and queries. So that it is clear to reproduce your feature extraction operation.
UMT is wonderful. Thanks for your contribution!!!

**Comment by yeliudev** [comment]
Many thanks for your suggestion! We are currently out of bandwidth for doing this, but a demo code will be provided later. In this stage, we recommend running your own feature extractors on public datasets and re-train the UMT model, as a from-scratch training only takes 2~3 hours on a single GPU.

**Comment by hpppppp8** [comment]
Thanks, I will try that later!
