### ISSUE TITLE
How to extract each modal feature.

### ISSUE THREAD

**Issue by Lvqin001** [TencentARC/UMT#2]
Hello, I want to test an original video, but I don't know your feature extraction method. Excuse me, will your code for extracting the features of image, audio and text be supplemented?

**Comment by yeliudev** [comment]
Thanks for your interest in our work. For models trained on QVHighlights, we directly adopted the visual and text features released by the original authors. You may refer to [this link](https://github.com/jayleicn/moment_detr#run-predictions-on-your-own-videos-and-queries) for the extraction process. The audio features are extracted using [PANN](https://zenodo.org/record/3987831/files/Cnn14_mAP%3D0.431.pth).
