### ISSUE TITLE
Hello, questions about text feature extraction。

### ISSUE THREAD

**Issue by Yangaiei** [TencentARC/UMT#20]
Hello, questions about text feature extraction。
        1、Is the model loaded when using [CLIP](https://github.com/openai/CLIP) to extract text features VIT-B /32?
        2、Is the text input when extracting text features using CLIP the value of "query" in the "highligiht_train_release.jsonl" file?

**Comment by yeliudev** [comment]
1. We directly adopted the text features from [Moment DETR](https://github.com/jayleicn/moment_detr). And they indeed used ViT-B/32 as mentioned [here](https://github.com/jayleicn/moment_detr/blob/main/run_on_video/run.py#L13).
2. Yes.

**Comment by Yangaiei** [comment]
1.  This is my code for text preprocessing as follows,I wonder if it is correct.

      ```
      device = "cuda" if torch.cuda.is_available() else "cpu"
      model, preprocess = clip.load("ViT-B/32", device=device)
      
      text = clip.tokenize(["some military patriots takes us through their safety procedures and measures"]).to(device)
      with torch.no_grad():
      text_features = model.encode_text(text)
      # print(text_features.shape)
      np.savez('text_features.npz', text_features)
      ```

2. My text extraction dimension is (1,52) and is different from that of your preprocessed text.  Is my thinking wrong?

```
print(text_features['arr_0'].shape)  # (1, 512)
####
q_features = np.load('qid6.npz') 
print(q_features.files)     # ['last_hidden_state', 'pooler_output']
print(q_features['last_hidden_state'].shape)   # (8, 512)
print(q_features['pooler_output'].shape)  # (512,)
```

@yeliudev

**Comment by Yangaiei** [comment]
Can you provide the specific code？

**Comment by yeliudev** [comment]
You may refer to the CLIP feature extractor in [this](https://github.com/jayleicn/moment_detr/tree/main/run_on_video) repo. For the QVHighlights dataset, we directly adopted the features provided by the original authors.

**Comment by Yangaiei** [comment]
Thank you very much. According to your tips, I have basically reproduced text feature extraction.😀
