### ISSUE TITLE
audio feature extraction

### ISSUE THREAD

**Issue by Yangaiei** [TencentARC/UMT#22]
hello，Audio feature extraction problem。
   1、 Feature extraction in audio data using [the output of this line in PANNS](https://github.com/qiuqiangkong/panns_inference/blob/013c0f6ab617c1be58f3b3564a6f2b17f5e1d2dc/panns_inference/models.py#L259)?

   2、 In qvhighlights dataset, do you directly extract features from 150 second audio?

**Comment by SYL-322** [comment]
1.  We use the [embedding](https://github.com/qiuqiangkong/panns_inference/blob/013c0f6ab617c1be58f3b3564a6f2b17f5e1d2dc/panns_inference/inference.py#L74)  line.

To be more specific, we extract features based on [inference](https://github.com/qiuqiangkong/panns_inference/blob/013c0f6ab617c1be58f3b3564a6f2b17f5e1d2dc/panns_inference/inference.py#L66) with an extra preprocess to remove the redundant part.


    def get_features(self, audio, feature_time=2, sr=32000):
        time = audio.shape[-1] / sr
        batches = int(time // feature_time)
        clip_sr = round(sr * feature_time)
        assert clip_sr >= 9920 
        audio = audio[:, :batches*clip_sr]
        
        audio_clips = np.reshape(audio[0], [batches, clip_sr])
        
        audio_clips = move_data_to_device(audio_clips, self.device)
        
        with torch.no_grad():
            output_dict = self.model(audio_clips, None)
            
        features = output_dict['embedding'].data.cpu().numpy()
        
        return features



`feature_time` is the needed clip duration and `sr` is the sample rate.

2. Yes.  We separate _.wav_ files directly from 150 second _.mp4_ files using _ffmpeg_, and extract audio features from _.wav_ files following PANN.
