### ISSUE TITLE
How do I use the trained models available in model zoo

### ISSUE THREAD

**Issue by AliButtarRB** [TencentARC/UMT#24]
Hi, 

Can you please provide a short example on how to use one of the models from the model zoo where I just pass in path to a video and relevant text query to get the highlights. I know the process might not be as straight forward as I am saying it to be but if there are any steps then please guide me into that direction and I will get started. 

Looking forward to your help.

Thanks

**Comment by yeliudev** [comment]
You may refer to the details of data pre-processing in each dataset's paper, and extract the features accordingly. Currently, this codebase only supports taking video and audio features as inputs, rather than raw videos.
