### ISSUE TITLE
save epoch problems

### ISSUE THREAD

**Issue by xiaohuihui-com** [TencentARC/UMT#27]
When I run the code, it is saved every epoch. Running this once will take up a lot of space. How should I set it up so that the parameters can be saved every specific epoch?

**Comment by yeliudev** [comment]
You may try to replace `hooks` in [runtime.py](https://github.com/TencentARC/UMT/blob/main/configs/_base_/runtime.py) as follows to save the model every 5 epochs.

```
hooks = [
    dict(type='CheckpointHook', interval=5),
    dict(
        type='EvalHook',
        high_keys=[
            'MR-full-mAP', 'HL-min-VeryGood-mAP', 'Rank1@0.5', 'Rank1@0.7',
            'Rank5@0.5', 'Rank5@0.7', 'mAP'
        ])
]
```
