### ISSUE TITLE
model test

### ISSUE THREAD

**Issue by Yangaiei** [TencentARC/UMT#28]
1.How to test highlight_test_release.jsonl text and How to output a prediction [like this](https://github.com/jayleicn/moment_detr/blob/main/standalone_eval/README.md#format).

2.Can you explain the metrics that appear in the validation set?
MR-long-mAP", "MR-middle-mAP", "MR-short-mAP", "HL-min-Fair-mAP", "HL-min-Fair-Hit1", "HL-min-Good-mAP"

**Comment by yeliudev** [comment]
1. You may simply add the following code at [this](https://github.com/TencentARC/UMT/blob/main/datasets/qvhighlights.py#L100) line to generate the file.
```
nncore.dump(collected, '<path-to-output.jsonl>')
exit()
```
3. The metrics and evaluation script are from [Moment-DETR](https://github.com/jayleicn/moment_detr). Please refer to their paper for details.

**Comment by Yangaiei** [comment]
1.Why am I using this command for validation sets? And I want to evaluate the test set.
 python tools/launch.py ./configs/qvhighlights/umt_base_200e_qvhighlights.py     --checkpoint ./work_dirs/umt_base_200e_qvhighlights/epoch_200.pth    --eval

2.What command do I want to use to evaluate the test set?

**Comment by Yangaiei** [comment]
For test set evaluation, do I need to add a [test set path?](https://github.com/TencentARC/UMT/blob/d3694d67675ae22ea8fb4eb17f491a0a928c90dc/configs/_base_/datasets/qvhighlights.py#L5)

**Comment by yeliudev** [comment]
Changing `highlight_val_release.jsonl` to `highlight_test_release.jsonl` at the 17th line should be fine.

**Comment by Yangaiei** [comment]
Do I need to change the validation set path to the test set path?

**Comment by Yangaiei** [comment]
I'll test it. Thank you very much!

**Comment by Yangaiei** [comment]
How is the predicted saliency scores (for all 2-sec clip) calculated? And why the predicted saliency scores (for all 2-sec clip) is negative.
```
>>>Predicted saliency scores (for all 2-sec clip):
'pred_saliency_scores': [7.459374984364331e-08, 2.9674001922330717e-08, 5.458217344767036e-08, 5.088656607199482e-08, 7.82326381454368e-08, 1.5096152594651358e-07, 5.8811878034248366e-08, 3.076957000303082e-08,...................., 0.0005385163240134716, 1.6341414266207721e-06, 1.4203264072421007e-05].
```

**Comment by Yangaiei** [comment]
1.I had an error running the test set.

![error](https://user-images.githubusercontent.com/92729149/192000389-599f854e-e75e-41af-bb00-5ab03d58d0cf.png)

2.Is there any other code that needs to be changed after changing the path?
`val=dict(
        type=dataset_type,
        label_path=data_root + 'highlight_test_release.jsonl',`

**Comment by yeliudev** [comment]
> How is the predicted saliency scores (for all 2-sec clip) calculated? And why the predicted saliency scores (for all 2-sec clip) is negative.
> 
> ```
> >>>Predicted saliency scores (for all 2-sec clip):
> 'pred_saliency_scores': [7.459374984364331e-08, 2.9674001922330717e-08, 5.458217344767036e-08, 5.088656607199482e-08, 7.82326381454368e-08, 1.5096152594651358e-07, 5.8811878034248366e-08, 3.076957000303082e-08,...................., 0.0005385163240134716, 1.6341414266207721e-06, 1.4203264072421007e-05].
> ```

These scores are not negative.

**Comment by yeliudev** [comment]
> 1.I had an error running the test set.
> 
> ![error](https://user-images.githubusercontent.com/92729149/192000389-599f854e-e75e-41af-bb00-5ab03d58d0cf.png)
> 
> 2.Is there any other code that needs to be changed after changing the path? `val=dict( type=dataset_type, label_path=data_root + 'highlight_test_release.jsonl',`

The results on test set can not be evaluated since they don't have annotations.

**Comment by Yangaiei** [comment]
> > How is the predicted saliency scores (for all 2-sec clip) calculated? And why the predicted saliency scores (for all 2-sec clip) is negative.
> > ```
> > >>>Predicted saliency scores (for all 2-sec clip):
> > 'pred_saliency_scores': [7.459374984364331e-08, 2.9674001922330717e-08, 5.458217344767036e-08, 5.088656607199482e-08, 7.82326381454368e-08, 1.5096152594651358e-07, 5.8811878034248366e-08, 3.076957000303082e-08,...................., 0.0005385163240134716, 1.6341414266207721e-06, 1.4203264072421007e-05].
> > ```
> 
> These scores are not negative.

How is the predicted saliency scores (for all 2-sec clip) calculated?

Is the predicted saliency scores (for all 2 second clips) the average of the three people?

**Comment by Yangaiei** [comment]
> > 1.I had an error running the test set.
> > ![error](https://user-images.githubusercontent.com/92729149/192000389-599f854e-e75e-41af-bb00-5ab03d58d0cf.png)
> > 2.Is there any other code that needs to be changed after changing the path? `val=dict( type=dataset_type, label_path=data_root + 'highlight_test_release.jsonl',`
> 
> The results on test set can not be evaluated since they don't have annotations.


I modified the annotations, but there was[ an error ](https://github.com/TencentARC/UMT/blob/d3694d67675ae22ea8fb4eb17f491a0a928c90dc/datasets/utils/evaluation.py#L146)running the test set.

![err](https://user-images.githubusercontent.com/92729149/192104074-703c6056-471a-464d-b8d3-a5065e282ef9.png)

**Comment by yeliudev** [comment]
1. Please refer to our paper for details about saliency scores prediction.
2. It is normal to have an error when running the code on test set. Just exit here, keep the output file, and upload it to the evaluation server.

**Comment by whateveryoutake** [comment]
> 1.I had an error running the test set.
> 
> ![error](https://user-images.githubusercontent.com/92729149/192000389-599f854e-e75e-41af-bb00-5ab03d58d0cf.png)
> 
> 2.Is there any other code that needs to be changed after changing the path? `val=dict( type=dataset_type, label_path=data_root + 'highlight_test_release.jsonl',`

I have the same problems with you, did you solve it?

**Comment by Yangaiei** [comment]
Thank you so much for your help!
