### ISSUE TITLE
Misalignment between video and audio for QVhighlight

### ISSUE THREAD

**Issue by wjun0830** [TencentARC/UMT#29]
THank you for the great work.

However, when I use the features provided by this repo,
some video and audio features are misaligned in their context length.

Example is attached below. It is described in the order of "vid, video shape, audio shape".
B3yOejNbNks_210.0_360.0 torch.Size([71, 2816]) torch.Size([70, 2048])

Can you provide how to align these features?

Thank you.
Best regards

**Comment by yeliudev** [comment]
Thanks for your interest in our work. We directly crop the features using the shorter length. For example, in your case, the last row of video features is discarded, so that both video and audio features have 70 vectors.

**Comment by wjun0830** [comment]
Thanks for the clarificatio!
