### ISSUE TITLE
How can download the data via wget

### ISSUE THREAD

**Issue by tuyunbin** [TencentARC/UMT#3]
Thanks for your great work. I wanna reproduce the work using the provided code and data. However, when I use wget  to dowload the file to my linux server, I met the error of: 
Resolving connectpolyu-my.sharepoint.com (connectpolyu-my.sharepoint.com)... 52.105.223.41
Connecting to connectpolyu-my.sharepoint.com (connectpolyu-my.sharepoint.com)|52.105.223.41|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-04-11 12:24:52 ERROR 403: Forbidden. 
I also try to use proxy, the above error still exists.

**Comment by yeliudev** [comment]
Thanks for your interest in our work! I'm afraid that no direct link can be generated from OneDrive now. Alternatively, you may want to use third-party command-line-based downloaders such as [DriveDownloader](https://github.com/hwfan/DriveDownloader). Simply copying the dataset links in README and pasting them into this tool shall work.

**Comment by tuyunbin** [comment]
Thanks, it works for me.
