### ISSUE TITLE
Text embedding on charadesSTA dataset and some minor questions

### ISSUE THREAD

**Issue by hsi1032** [TencentARC/UMT#30]
Hi, first of all, thanks for your great work!

I plan to perform the experiments on charadesSTA dataset with the features you provide,
but I notice that there is no text embedding files, although other features (videos, optical flows, audio) are available.

Can you provide the text embedding you used for your experiments?

Also, I have some minor questions about data preprocessing.
Similar to the Issue in https://github.com/TencentARC/UMT/issues/29#issue-1410050684,
I found the length of optical flow features is different from that of video features.

Did you simply crop the feature using a shorter length, same as the audio features?

Thanks,

**Comment by yeliudev** [comment]
Hi @hsi1032, thanks for your interest in our work.

We extract the text embeddings using torchtext (see [here](https://github.com/TencentARC/UMT/blob/main/datasets/charades.py#L81:L85)). As for optical flow, we crop the features using a shorter length just like audio.

**Comment by hsi1032** [comment]
Thank you for prompt reply!

I missed the details in data preprocessing code, sorry for bothering.

**Comment by hsi1032** [comment]
Hi, sorry for bothering you again but I want to ask some question additionally.

When I preprocess the charadesSTA dataset in my own code, I met some issues.
Specifically, I wonder how to match the moment label and its corresponding features.

For example, some query label of 0A8CF.mp4 in charadesSTA dataset has information as below.
- video length: 33 seconds
- moment labels: [25.5, 33.0]
- rgb feature shape: (190, 4096)
- opt feature shape: (194, 4096)

As noted in the original dataset repository, 
I understand the features have a 6 times longer length than the video length.

However, the video length x 6 doesn't identical to the length of rgb and opt features.

May I ask how you match these moments and video/audio features precisely?

Thanks,

**Comment by yeliudev** [comment]
We simply discarded the video length (33s) and followed the rule that each feature represents 1/6 second.

**Comment by hsi1032** [comment]
Okay, I understood.

Thanks a lot!
