### ISSUE TITLE
 results visualized

### ISSUE THREAD

**Issue by Yangaiei** [TencentARC/UMT#31]
1、How are the results visualized?

![1668158260458](https://user-images.githubusercontent.com/92729149/201307678-7e9450ad-9221-46aa-a5bf-7133a203ccdb.png)

2、Does the Y-axis of the line plot represent the saliency scores of the prediction？

**Comment by yeliudev** [comment]
1. The figures are drawed according to the outputs from UMT.
2. Yes.

**Comment by Yangaiei** [comment]
Thank you very much!
