### ISSUE TITLE
What is the horizontal coordinate of Figure 4 in the paper? What does it represent?

### ISSUE THREAD

**Issue by G-Apple1** [TencentARC/UMT#32]
![image](https://user-images.githubusercontent.com/62458945/203055619-7a4a7525-ffd3-423b-ae6a-59c0f5a707ae.png)

**Comment by yeliudev** [comment]
The x-axis represents time (in seconds).

**Comment by G-Apple1** [comment]
> The x-axis represents time (in seconds).

The data is divided into a clip of 5s, so how to understand it as time seconds? Does the time representation of this horizontal axis have nothing to do with data division?

**Comment by yeliudev** [comment]
> the time representation of this horizontal axis have nothing to do with data division?

Yes, the time representation of this horizontal axis has nothing to do with data division.
