### ISSUE TITLE
Pretraining Problem

### ISSUE THREAD

**Issue by Lonicer** [TencentARC/UMT#33]
Could you please provide a specific method of pre-training? I am getting the following error using your pretraining command:
![image](https://user-images.githubusercontent.com/70836946/203215386-c12ffa6e-3f90-4c88-b0ac-486a7a6f62d8.png)

**Comment by yeliudev** [comment]
It seems that this is not a command-related problem. I cannot reproduce your error in my environment. Please double-check whether your environment is aligned with the one in README.

**Comment by Lonicer** [comment]
Hello, I will report an error when I use multi-GPU training. The command is as follows. I have recreated a conda virtual environment and downloaded the required packages using the code you provided:
torchrun --nproc_per_node=2 tools/launch.py /home/4TDisk/zmy/repo_test/UMT/configs/qvhighlights/umt_base_200e_qvhighlights.py
Is it a problem with torch run?







勾陈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TencentARC/UMT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月22日(星期二) 中午12:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TencentARC/UMT] Pretraining Problem (Issue #33)





 
It seems that this is not a command-related problem. I cannot reproduce your error in my environment. Please double-check whether your environment is aligned with the one in README.

**Comment by yeliudev** [comment]
> Hello, I will report an error when I use multi-GPU training. The command is as follows. I have recreated a conda virtual environment and downloaded the required packages using the code you provided: torchrun --nproc_per_node=2 tools/launch.py /home/4TDisk/zmy/repo_test/UMT/configs/qvhighlights/umt_base_200e_qvhighlights.py Is it a problem with torch run? 勾陈 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "TencentARC/UMT" ***@***.***&gt;; 发送时间:&nbsp;2022年11月22日(星期二) 中午12:31 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [TencentARC/UMT] Pretraining Problem (Issue #33) It seems that this is not a command-related problem. I cannot reproduce your error in my environment. Please double-check whether your environment is aligned with the one in README. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Please try to install the up-to-date [nncore](https://github.com/yeliudev/nncore) from source if you are using `torch>=1.12`.
