### ISSUE TITLE
TVSum training problem

### ISSUE THREAD

**Issue by GYGWG** [TencentARC/UMT#37]
Hi. Thanks for your great work.
When I am trying to train the model under TVsum dataset I got this error:

![2023-03-13 22-59-18 的屏幕截图](https://user-images.githubusercontent.com/18219764/224740766-7452ca50-e65c-43d9-9eeb-1733ad7acb5a.png)

The command I used is:
```
torchrun --nproc_per_node=4 tools/launch.py configs/tvsum/umt_small_500e_tvsum_ga.py
```
And the environment of my workspace:

![2023-03-13 23-03-06 的屏幕截图](https://user-images.githubusercontent.com/18219764/224741819-13f51d69-7d6d-4e71-83ef-2beb494747e3.png)

Please check if you can reproduce the same result. Thanks.

**Comment by yeliudev** [comment]
We used only a single GPU for all the experiments except ASR pre-training on QVHighlights. You may use the following command instead.

```
python tools/launch.py configs/tvsum/umt_small_500e_tvsum_ga.py
```

**Comment by GYGWG** [comment]
Awesome!
