### ISSUE TITLE
Something seems wrong in the head.py

### ISSUE THREAD

**Issue by NNNNAI** [TencentARC/UMT#4]
Thanks for sharing your wonderful work!!!!!
I am running the UMT on qvhightlight dataset following yout instruction by running:
```
python tools/launch.py ./configs/qvhighlights/umt_base_200e_qvhighlights.py
```
However, I got such a error report:
![image](https://user-images.githubusercontent.com/30747212/166852404-9854ceb5-444b-4795-abd0-b1aa2508bdb1.png)

The shape of center_pred I got is [32,75], which do not have a length dim,and I try to fix it by simpely adding a length dim:
```
 center_pred = center_pred.unsqueeze(1)
```
It reported another bug:
![image](https://user-images.githubusercontent.com/30747212/166852568-6f362f8c-cd07-4c16-8724-38ee3e05b8df.png)

Could you help me to solve such a problem? Thanks again, have a nice day～.

**Comment by yeliudev** [comment]
Hi @NNNNAI! Thanks for your interest in our work.

The shape of `center_pred` is correct, it should be [32, 75]. I'm afraid that I can not reproduce the bug in my environment. Could you please try it again with `Python>=3.10` and `torch>=1.11`, as the `F.max_pool1d` API may change among different PyTorch versions?
