### ISSUE TITLE
Audio feature extraction

### ISSUE THREAD

**Issue by GYGWG** [TencentARC/UMT#40]
Hi. Question about audio feature extraction.

I have read issue #22.  I am wondering:

1. Why is `sr` always 32000? What does it mean?
2. If I want to extract the feature for every frame from the audio, what should the `feature_time` and `sr` be in this case?

**Comment by yeliudev** [comment]
Sorry for the late reply. The audio extraction process was done by our second author, who has left the company and did not preserve the code. Theoretically, any audio feature extraction method that could produce the same number of tokens as videos should work in our cases.
