### ISSUE TITLE
Inference mode

### ISSUE THREAD

**Issue by Rj-batista** [TencentARC/UMT#42]
Hi,

Iam a little confuse about how to use your model
First of all i wanted some clarification about models. 
I want to try with my own video with the [UMT-B V+A](https://github.com/TencentARC/UMT/configs/charades/umt_base_va_100e_charades.py) model with [Charades-STA](https://arxiv.org/abs/1705.02101) by giving it a Query and a video.
In your repo you only mention training, eval and for the test part i didn't see a test configuration after i lookup at your code
Can you explain with the model mentionned above on how to make a prediction if i have a video and a query ?

Thank you

**Comment by yeliudev** [comment]
Thanks for your interest in our work. Currently, we only provide the code for training and testing with standard dataset pipelines. If you want to test on your own video and query, you may need to write the inference pipeline by yourself, according to the pre-processing part of datasets.

**Comment by Rj-batista** [comment]
I have a final question about your model 
In your paper you mention that the query can also be used to search from audio feature and make audio prediction
I am interested to use that feature and i didn't know exactly what model should i take from the list you gave in the model zoo section in you readme or the one in the config section.
What model should i use to be able to make audio prediction of a video in the list of available pre-trained model or config model you give.

Thank you

**Comment by yeliudev** [comment]
If you want to run the audio-only version of UMT, you may modify `configs/_base_/models/umt_small.py` by setting `model['video_enc'] = None` and `model['cross_enc'] = None`, and use the `configs/qvhighlights/umt_base_200e_qvhighlights.py` directly.

**Comment by Rj-batista** [comment]
And in the case i want to use both audio and query feature ?

**Comment by yeliudev** [comment]
The modification above is for using both audio and query features.

**Comment by Rj-batista** [comment]
Ok, i will close the issue with this message
Thank you for the time and the answers
