### ISSUE TITLE
Error. TypeError: '>=' not supported between instances of 'DataContainer' and 'int'

### ISSUE THREAD

**Issue by GuangtaoLyu** [TencentARC/UMT#43]
When I train or pre-train the model, the error "TypeError: '>=' not supported between instances of 'DataContainer' and 'int' " happens.

But the eval can work.

If I use .data to get the tensor,  the train and pre-train can work, but the eval can't work.

"
UMT/models/model.py", line 34, in forward
    mask = torch.where(data['saliency'] >= 0, 1, 0)
TypeError: '>=' not supported between instances of 'DataContainer' and 'int'

"

**Comment by yeliudev** [comment]
Please try again using `python>=3.8`.

**Comment by GuangtaoLyu** [comment]
> When I train or pre-train the model, the error "TypeError: '>=' not supported between instances of 'DataContainer' and 'int' " happens.
> 
> But the eval can work.
> 
> If I use .data to get the tensor, the train and pre-train can work, but the eval can't work.
> 
> " UMT/models/model.py", line 34, in forward mask = torch.where(data['saliency'] >= 0, 1, 0) TypeError: '>=' not supported between instances of 'DataContainer' and 'int'
> 
> "

Thank you. It seems due to the torch 2.0.1. now I solved it.
