### ISSUE TITLE
result of QVHighlights val set

### ISSUE THREAD

**Issue by EasonXiao-888** [TencentARC/UMT#45]
Tanks for your great work. Could you please provide the pred.json in the val set on QVHighlights dataset?

**Comment by c1d2y3** [comment]
你好，问题解决了吗？运行launch.py .\configs\qvhighlights\umt_base_pretrain_100e_asr.py报错

**Comment by EasonXiao-888** [comment]
您好，我还没有解决这个问题，我运行的是 python tools/launch.py configs/qvhighlights/umt_base_200e_qvhighlights.py --checkpoint umt_base_200e_qvhighlights-9a13c673.pth --eval 希望获得对val数据集的预测结果 但是报错如下：
![image](https://github.com/TencentARC/UMT/assets/88182633/6d94d8ed-fa58-4716-b312-d4e213c896e6)
