### ISSUE TITLE
Audio feature extraction

### ISSUE THREAD

**Issue by SalmaMohamedElsayed** [TencentARC/UMT#48]
Hello, regarding the preprocessing done for audio feature extraction, 
1. Can you provide the code that calls get_features function provided in issue #22 
2. Do you call this method for every audio file in youtube highlights dataset as there are some files producing errors.
3. In batches computation, why do you do integer division and then cast it to integer ?
4. How to identify the values for feature_time provided in issue #22 
5. I am trying to regenerate the audio features of Youtube Highlights using PANN, can you provide the steps that you did for feature extraction.
Thanks in advance

**Comment by yeliudev** [comment]
I'm deeply sorry for the late reply. The audio extraction process was done by our second author, who has left the company and did not preserve the code. The `feature_time` is just computed by `1 / fps_of_the_video_stream`. Theoretically, any audio feature extraction method that could produce the same number of tokens as videos should work.
