### ISSUE TITLE
about model

### ISSUE THREAD

**Issue by MasterBeeee** [TencentARC/UMT#51]
您好，感谢你们的工作，在拜读你们的文章时，我有一个问题，在图二中，如果视频和音频中有一个不可用时，对应的uni-model encoder和cross-model encoder将会停用
<img width="950" alt="image" src="https://github.com/TencentARC/UMT/assets/77255816/e22a8ebe-7e42-48fd-8d96-9d2b039c27f6">
那么
 1.如果其中一个不可用，例如音频，那是否代表视频在Ev提取过特征后，直接进入query generator和 query decoder 
2.只有video和audio都输入时，cross-model encoder才是可用的

**Comment by yeliudev** [comment]
Thanks for your interest in our work! You are right, the cross-modal encoder is activated only when both video and audio encoders are used. When audio is not available, the video features from the video encoder will be directly sent to query generator & decoder.
