### ISSUE TITLE
Model Instability

### ISSUE THREAD

**Issue by SalmaMohamedElsayed** [TencentARC/UMT#52]
When I run the model with the pre-extracted features you provided using the same pipeline provided, I do not get the same results you provided in the paper in every run

**Comment by yeliudev** [comment]
Thanks for reporting. This is expected as the datasets are relatively small. We provided a `--seed` option to set and freeze the random seed during training, which would make you get the same results every run.

**Comment by SalmaMohamedElsayed** [comment]
Thank you for replying, can you suggest a value for the seed to replicate your results

**Comment by yeliudev** [comment]
I'm afraid that we cannot provide an exact value, as we don't have the original full training logs now (only metrics [here](https://huggingface.co/yeliudev/UMT/resolve/main/checkpoints/umt_base_200e_qvhighlights.json)), and random seeds could only make the training deterministic on the same machine. What we can provide is that we generated the 8-digit random seed using [this](https://github.com/yeliudev/nncore/blob/d688bda884f8c1426b17d4c16573fc5b04629145/nncore/engine/utils.py#L82:L106) method.

Besides, if you are looking for a good performing MR/HD model, I would recommend trying our [new project](https://github.com/yeliudev/R2-Tuning).
