### ISSUE TITLE
.json annotation

### ISSUE THREAD

**Issue by Lynneyyq** [TencentARC/UMT#8]
Hello, I am very interested in your research. 
Can you give a detailed description of dataset annotation files, such as YouTube, TVSum?Thanks a lot.

**Comment by yeliudev** [comment]
For YouTube Highlights and TVSum datasets, each `.json` annotation file contains a `dict`, with the video ids as keys and annotations as values. The highlight saliency scores actually used are in the `match` (YouTube Highlights) or `anno` (TVSum) fields. You may refer to the dataset loaders ([1](https://github.com/TencentARC/UMT/blob/main/datasets/youtube.py), [2](https://github.com/TencentARC/UMT/blob/main/datasets/tvsum.py)) for details.
