### ISSUE TITLE
How to prepare the data

### ISSUE THREAD

**Issue by Lynneyyq** [TencentARC/UMT#9]
I used the feature extraction method you [provided](https://github.com/v-iashin/video_features), and all the feature dimensions obtained are [1,1024]. They are different from the feature dimensions you gave. What modifications have you made? I would like to know what are the requirements for the feature dimension derived from the model?
Thank you so much!

**Comment by yeliudev** [comment]
For I3D features, we simply concatenated the visual and optical stream outputs, thus each final feature vector should have the shape of `1 x 2048`.
